/**
 * Downloads the latin subset of every bundled font family from Google Fonts and
 * writes them, plus a self-contained @font-face stylesheet, into public/fonts.
 *
 * santi.tab ships fonts locally so the new tab renders instantly, works
 * offline, and never phones home to fonts.googleapis.com on every tab open.
 *
 * Run with: npm run fonts
 */
import { mkdir, readdir, rm, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const OUT_DIR = resolve(ROOT, "public/fonts")

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

// Only the subsets we actually render. Keeps the bundle at a few dozen KB.
const KEPT_SUBSETS = new Set(["latin", "latin-ext"])

const FAMILIES = [
  "Poppins:wght@400;500;600;700",
  "Montserrat:wght@400;500;600;700",
  "Inter:wght@400;500;600;700",
  "Space Grotesk:wght@400;500;600;700",
  "JetBrains Mono:wght@400;600",
]

const cssUrl =
  "https://fonts.googleapis.com/css2?" +
  FAMILIES.map((f) => `family=${encodeURIComponent(f)}`).join("&") +
  "&display=swap"

const slug = (value) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")

async function main() {
  const res = await fetch(cssUrl, { headers: { "User-Agent": UA } })
  if (!res.ok) throw new Error(`Google Fonts responded ${res.status}`)
  const css = await res.text()

  await rm(OUT_DIR, { recursive: true, force: true })
  await mkdir(OUT_DIR, { recursive: true })

  // Each @font-face is preceded by a `/* subset */` comment.
  const blocks = [...css.matchAll(/\/\* (\S+) \*\/\s*(@font-face \{[^}]*\})/g)]
  if (!blocks.length) throw new Error("No @font-face blocks found in response")

  const out = []
  let downloaded = 0

  for (const [, subset, block] of blocks) {
    if (!KEPT_SUBSETS.has(subset)) continue

    const family = block.match(/font-family:\s*'([^']+)'/)?.[1]
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? "400"
    const style = block.match(/font-style:\s*(\w+)/)?.[1] ?? "normal"
    const remote = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1]
    if (!family || !remote) continue

    const file = `${slug(family)}-${weight}-${subset}.woff2`
    const font = await fetch(remote, { headers: { "User-Agent": UA } })
    if (!font.ok) throw new Error(`${remote} responded ${font.status}`)

    await writeFile(
      resolve(OUT_DIR, file),
      Buffer.from(await font.arrayBuffer())
    )
    downloaded++

    out.push(
      block
        .replace(/url\(https:\/\/[^)]+\.woff2\)/, `url(./${file})`)
        .replace(/@font-face \{/, "@font-face {\n  font-display: swap;")
    )
  }

  await writeFile(
    resolve(OUT_DIR, "fonts.css"),
    `/* Generated by scripts/fetch-fonts.mjs -- do not edit by hand. */\n\n` +
      out.join("\n\n") +
      "\n"
  )

  const files = await readdir(OUT_DIR)
  console.log(`[santi.tab] wrote ${downloaded} woff2 files (${files.length} total in public/fonts)`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
